### ISSUE TITLE
Break in code-gen for external types used in path/query params

### ISSUE THREAD

**Issue by tabboud** [palantir/conjure-go#247]
## What happened?
A panic was encountered after upgrading from `v6.5.0` to `v.6.6.0`, which includes the code-gen change to jennifer from goastwriter.
Of note, this appears when an API uses an external type in either path or query parameters.

```
panic: unrecognized type BackupId (string)

goroutine 1 [running]:
github.com/palantir/conjure-go/v6/conjure.astForDecodeHTTPParamInternal(0xc00038fe60, {0xc00023a588, 0x8}, {0x1465920, 0xc00041e080}, {0xc00023a588, 0x8}, {0x145a6f0, 0xc000389a58}, 0x0)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/serverwriter.go:387 +0x980d
github.com/palantir/conjure-go/v6/conjure.astForDecodeHTTPParam(...)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/serverwriter.go:289
github.com/palantir/conjure-go/v6/conjure.astForHandlerMethodQueryParam(0x0, 0xc000028d80)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/serverwriter.go:246 +0x1247
github.com/palantir/conjure-go/v6/conjure.astForHandlerMethodQueryParams(0x0, {0xc00034e378, 0x1, 0x0})
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/serverwriter.go:234 +0x38
github.com/palantir/conjure-go/v6/conjure.astForHandlerMethodBody(0x100e367, {0xc0004e9020, 0xb}, 0xc0003a4bb0)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/serverwriter.go:149 +0x115
github.com/palantir/conjure-go/v6/conjure.astForHandlerMethods.func1(0xc00005ad80)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/serverwriter.go:137 +0x2c
github.com/dave/jennifer/jen.(*Statement).BlockFunc(0xc0002beee8, 0xc0005cb6a8)
        /Volumes/git/go/src/github.com/palantir/conjure-go/vendor/github.com/dave/jennifer/jen/generated.go:234 +0x89
github.com/palantir/conjure-go/v6/conjure.astForHandlerMethods(0xc00033e1e0)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/serverwriter.go:136 +0x1265
github.com/palantir/conjure-go/v6/conjure.writeServerType(0xc000285980, 0xc00033e1e0)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/serverwriter.go:54 +0x597
github.com/palantir/conjure-go/v6/conjure.GenerateOutputFiles({0x1, {0x1edea50, 0x0, 0x0}, {0xc00019a540, 0x4, 0x4}, {0xc0001f4400, 0x1, 0x4}, ...}, ...)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/conjure.go:95 +0x1005
github.com/palantir/conjure-go/v6/conjure.Generate({0x1, {0x1edea50, 0x0, 0x0}, {0xc00019a540, 0x4, 0x4}, {0xc0001f4400, 0x1, 0x4}, ...}, ...)
        /Volumes/git/go/src/github.com/palantir/conjure-go/conjure/conjure.go:29 +0x65
main.run({0x13d4413, 0x480}, {0x13b2b14, 0x6})
        /Volumes/git/go/src/github.com/palantir/conjure-go/integration_test/testgenerated/generate.go:61 +0x14f
main.main()
        /Volumes/git/go/src/github.com/palantir/conjure-go/integration_test/testgenerated/generate.go:33 +0xa5
exit status 2
```

## What did you want to happen?
Code should be generated as it was prior to `v6.6.0`

**Comment by tabboud** [comment]
I was able to repro this issue with an integration test with the following external type added. Additionally, I have ported this back to v6.5.0 and the server is generated as expected.

```diff
diff --git a/integration_test/testgenerated/server/server-service.yml b/integration_test/testgenerated/server/server-service.yml
index a0e875c..5189909 100644
--- a/integration_test/testgenerated/server/server-service.yml
+++ b/integration_test/testgenerated/server/server-service.yml
@@ -6,6 +6,10 @@ types:
     OtherMarker:
       external:
         java: com.palantir.logsafe.OtherMarker
+    BackupId:
+      base-type: string
+      external:
+        java: com.palantir.service.api.BackupId
   definitions:
     default-package: api
     objects:
@@ -119,6 +123,19 @@ services:
           myQueryParam1:
             type: list<uuid>
             param-type: query
+      queryParamExternalType:
+        http: GET /externalTypeQueryVar
+        auth: header
+        args:
+          backupId:
+            type: BackupId
+            param-type: query
+      pathParamExternalType:
+        http: POST /path/{backupId}
+        auth: header
+        args:
+          backupId:
+            type: BackupId
       postPathParam:
         http: POST /path/{myPathParam1}/{myPathParam2}
         auth: header
```
